### ISSUE TITLE
Mark current player on the field

### ISSUE THREAD

**Issue by TobiasKozel** [RAlbiez/SchnappsAndLiquor#10]

**Comment by TheForcer** [comment]
My first idea is to use a pulse/blinking effect on the dot of the current player.

I want to change this line https://github.com/RAlbiez/SchnappsAndLiquor/blob/9e377d40d722295dbcdfa88b7d549e4aa26875b9/Frontend/src/app/components/game/field/field.component.html#L9 into

`<div [style.background]="player.sColor" [class.pulse]="isPlayerTurn()" class="color-dot"></div>`

Afterwards the game grid won't render correctly anymore. If I replace the function call with "true", it's working though:

`<div [style.background]="player.sColor" [class.pulse]="true" class="color-dot"></div>`

What am I doing wrong here @TobiasKozel ?
