### ISSUE TITLE
Kick doesn't work

### ISSUE THREAD

**Issue by TobiasKozel** [RAlbiez/SchnappsAndLiquor#14]

**Comment by TheForcer** [comment]
Well, it does work in the current state (Just tested on the offical instance with several devices and connections). Did we have some edge case back then? Do you remember what didn't work by chance?

**Comment by RAlbiez** [comment]
I think the goal was to kick "stranded" players that were created by someone disconnecting and rejoining under a different name, did you test that aswell?

**Comment by TheForcer** [comment]
Right, that's the issue we had. And sure enough - once someone left the game, you cannot kick the stale player/icon. I'll take a look at this now.
