### ISSUE TITLE
Check if there's a websocket timeout

### ISSUE THREAD

**Issue by TobiasKozel** [RAlbiez/SchnappsAndLiquor#9]

**Comment by TheForcer** [comment]
Changing the timeout variable definitely did help, we are now looking at a rough 10min timeout, which should be plenty for most cases -> https://github.com/RAlbiez/SchnappsAndLiquor/commit/c5d01d9a8938369ae70a6edbcfd02172098dc994#diff-3814c1ef3b40f39e74736f940b18062cde00ca3e95b7d8360871c7d569a5f3eeR847

**Comment by TheForcer** [comment]
This wasn't really working. After some tests, adding `proxy_read_timeout 30m;` to the location block of the nginx proxy config seems to work fine.
